server:
  port: 8002
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.torchcqs.cn:3306/torch?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: cjsd10-3
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #邮件发送配置，目前是小码
  mail:
    host: smtp.qq.com
    username: 3057179865@qq.com
    password: lyduypdnolpodcfj
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 127.0.0.1
    port: 6379
#    password:
#    lettuce:
#      pool:
#        max-active:
#        max-idle:
#        max-wait:
#      shutdown-timeout:
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #  xml文件所在位置
  type-aliases-package: com/torch/app/entity #别名文件位置

wx:
  appid: wx49292af0e1fb1fc4
  secret: a382df1cb070d7754fb2023dfe209b8b